import React from 'react';
import { Card } from '@/components/ui/Card';
import { FileText, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/Button';

interface TermsPageProps {
  onNavigate?: (route: string) => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      {/* Back button */}
      <div>
        <Button
          variant="ghost"
          size="sm"
          leftIcon={<ArrowLeft className="w-4 h-4" />}
          onClick={() => (onNavigate ? onNavigate('home') : null)}
        >
          Back to Home
        </Button>
      </div>

      <div className="space-y-3 text-center sm:text-left">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-card-elevated border border-border-subtle text-xs text-brand-cyan font-semibold">
          <FileText className="w-3.5 h-3.5" />
          <span>Legal Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-text-primary tracking-tight">
          Terms of Service
        </h1>
        <p className="text-xs sm:text-sm text-text-muted">
          Last Updated: August 31, 2026 • ClearCut AI Platform
        </p>
      </div>

      <Card variant="default" className="p-6 sm:p-10 space-y-8 text-sm text-text-secondary leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <span className="text-brand-cyan">1.</span> Acceptance of Terms
          </h2>
          <p>
            By accessing or using ClearCut AI (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not access the service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <span className="text-brand-cyan">2.</span> Service Description & Ephemeral Storage
          </h2>
          <p>
            ClearCut AI provides automated, deep-learning-based image background removal. ClearCut AI does not store user-uploaded images permanently. In accordance with our Ephemeral Storage Policy, source and processed images are automatically purged within 24 hours of upload.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <span className="text-brand-cyan">3.</span> Intellectual Property & Commercial Use
          </h2>
          <p>
            You retain all ownership and copyright rights to the original images you submit. Processed PNG cutouts generated by ClearCut AI may be used for personal, commercial, and e-commerce purposes without royalty fees or watermarks.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <span className="text-brand-cyan">4.</span> Payments, Credits & bKash Gateway
          </h2>
          <p>
            Payments made via the official bKash Payment Gateway in Bangladeshi Taka (BDT) are final and credited immediately to your account. Credit packs are non-transferable and do not expire.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <span className="text-brand-cyan">5.</span> Prohibited Content
          </h2>
          <p>
            Users are strictly prohibited from uploading unlawful, infringing, abusive, or explicitly harmful materials. Any account violating these terms may be immediately suspended without refund.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <span className="text-brand-cyan">6.</span> Limitation of Liability
          </h2>
          <p>
            ClearCut AI is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for incidental or consequential damages resulting from service interruptions or third-party network issues.
          </p>
        </section>
      </Card>
    </div>
  );
};
